name: manual-CI/CD

on:
  workflow_dispatch:
    inputs:
      VERSION:
        required: false
        default: "1.0"
        type: string
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: azure/docker-login@v1
        with:
          login-server: lottechemicalacr.azurecr.io
          username: ${{ secrets.acr_username }}
          password: ${{ secrets.acr_password }}

      - name: Build and push image to ACR
        id: build-image
        run: |
          docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t lottechemicalacr.azurecr.io/php:${{ github.event.inputs.VERSION }} --label dockerfile-path=Dockerfile
          docker push lottechemicalacr.azurecr.io/php:${{ github.event.inputs.VERSION }}

      - uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.aks_kubeconfig }}
        id: login

      - name: Create namespace
        run: |
          namespacePresent=`kubectl get namespace | grep php | wc -l`
          if [ $namespacePresent -eq 0 ]
          then
              echo `kubectl create namespace php`
          fi
      # - uses: azure/k8s-create-secret@v1
      #   with:
      #     namespace: php
      #     container-registry-url: lottechemicalacr.azurecr.io
      #     container-registry-username: ${{ secrets.acr_username }}
      #     container-registry-password: ${{ secrets.acr_password }}
      #     secret-name: phpdockerauth

      - uses: azure/k8s-deploy@v1.2
        with:
          namespace: php
          manifests: |
            manifests/deployment.yml
            manifests/service.yml
          images: |
            lottechemicalacr.azurecr.io/php:${{ github.event.inputs.VERSION }}
